### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by vaunapuu** [buerokratt/Classifier#1]
~~AS AN ADMIN of Classifier
I WANT TO ADD others to Classifier and so I need to enter their Estonian personal ID CODE (Isikukood) and ROLE 
SO THAT they can access Classifier.~~

AS A Service Manager
I WANT TO be able to add, edit and delete users and their permissions
SO THAT I could be in total control of Classifier users

#### Adding, editing and removing new users

- [ ] New users can be added through modal
- [ ] New users can be edited through modal
- [ ] New users can be removed through modal
- [ ] Duplications are avoided based on user's personal code

#### User authentication

- [ ] TARA is used for user authentication

#### Permissions

- [ ] The first user to log in after initial deployment get `administrative` privileges
- [ ] User groups are administrated by any user with `administrative` privileges
- [ ] Users can be part of any number of user groups
- [ ] Role-based access control is applied on all requests

#### To delete

- [ ] ~#2~
- [ ] ~#3~
- [ ] ~#5~
- [ ] ~#52~
- [ ] ~#6~
- [ ] ~#7~
- [ ] ~#8~

**Comment by turnerrainer** [comment]
We'll use an existing Bürokratt's user management system, most likely as a replicated system. TARA integration will also be covered with this.
