### ISSUE TITLE
Graphical User Interface

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Classifier#106]
AS A Product Owner
I WANT Classifier to have a graphical user interface (GUI)
SO THAT it could be used by NLP trainers, CSAs, etc.

### Acceptance Criteria

- [ ] Based on Figma designs
- [ ] Figma designs used as example screenshots in this issue are subject to change
- [ ] Existing Bürokratt's GUI components will be re-used
- [ ] When necessary, new components will be developed based on the same CVI and technical requirements as Bürokratt's current GUI components
- [ ] Alerts as modals for different events (TBA)
- [ ] Server-side pagination applied
- [ ] List results based on name (alphabetically asc/desc)
- [ ] List results based on timestamp (asc/desc)

#### Scope

- [ ] #121
- [ ] #122
- [ ] #123
- [ ] #124
- [ ] #125
- [ ] #126
- [ ] #127
