### ISSUE TITLE
Synthetic data generator

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Classifier#117]
AS AN Architect
I WANT TO have a stand-alone synthetic data generator as a service
SO THAT I could use its functionalities and replace/upgrade it if necessary

### Acceptance Criteria

- [ ] Synthetic data is generated based on required data class
- [ ] Based on existing free-source LLMs
- [ ] Data classes defined by fine-tuning LLM prompts
- [ ] `README.md` to cover the deployment of the system
- [ ] Documentation with sample queries to adopt the service

#### Prerequisites

- [ ] Suitable synthetic data generator(s) proposed by the Partner
- [ ] Suitable synthetic data generator confirmed by the Client

#### GUI

- [ ] GUI is out of scope of this issue

#### DSL

- [ ] Creating custom `regex` rules for specific data classes is out of scope
