### ISSUE TITLE
User management for Classifier

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Classifier#121]
AS A Product Owner
I WANT TO have the functionality for user management for Classifier
SO THAT their permissions, etc. could be maintained

### Acceptance Criteria

- [ ] Re-using Bürokratt's current [user management](https://admin.test.buerokratt.ee/chat/users) GUI as part of [Bürokatt Backoffice](https://github.com/buerokratt/Buerokratt-Chatbot)

![image](https://github.com/buerokratt/Classifier/assets/90505798/14fc75ed-76b3-40db-938e-5f2f97506571)

- [ ] Classifier-specific user permissions added to generic Bürokratt's user management

![image](https://github.com/buerokratt/Classifier/assets/90505798/c88e5f9a-fb55-407e-b34f-29ff803c57d9)

- [ ] Classifier-specific user management on back-end level is not foreseen
- [ ] Existing user management- and permission-specific backend solutions are used
