### ISSUE TITLE
Enrich datasets with synthetic data

### ISSUE THREAD

**Issue by vaunapuu** [buerokratt/Classifier#30]
AS A Data Scientist
I WANT TO enrich existing datasets
SO THAT I could increase the precision of the data model

### Acceptance Criteria

- [ ] Use #117 as an internal source to enrich existing datasets
- [ ] All changes on datasets must end with version number update

#### GUI

- [ ] #120

#### DSL

- [ ] `REST` `POST` service `/synthetic-data/generate` with passing `data_class` and `size` as parameters
- [ ] #119
- [ ] #118

#### Scope

- [ ] All functionalities can be used via GUI
- [ ] All functionalities can be used as REST endpoints
- [ ] Data enrichment with external sources is out of scope
