### ISSUE TITLE
Handling attachments

### ISSUE THREAD

**Issue by vaunapuu** [buerokratt/Classifier#79]
AS AN ADMIN
I WANT TO receive all the email attachments that are relevant
SO THAT the data model can assign classes with more precision

- [ ] Detect all attachments of incoming email
- [ ] Filter out all unnecessary attachments (company logo, email signature etc)
- [ ] Only attachment name and extension is needed, attachments don't need to be read in
