### ISSUE TITLE
Maintain Data Classes

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Classifier#85]
AS A Data Scientist
I WANT TO maintain different datasets and group them as Data Classes
SO THAT Data Classes of specific type (e.g. email, dates, etc.) would be centrally maintained and could be used in other parts of the Classifier

### Acceptance Criteria

- [ ] Assign attachments as sample datasets specific to given Data Class
- [ ] Assign external sample datasets to specific Data Classes via API endpoints

#### GUI

- [ ] #111

#### DSL

- [ ] #112
- [ ] #113
- [ ] #114

#### Access

- [ ] Role-based access control is applied for every action
- [ ] Permissions per role can not be defined via GUI
