### ISSUE TITLE
Remove variations from raw text

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Classifier#87]
AS A Data Scientist
I WANT TO remove variations from raw text
SO THAT input of much higher quality could be used in data models

### Acceptance Criteria

> Detailed solutions of this epic will be defined in cooperation by the client and the service provider

- [ ] Input text tokenization
- [ ] Input text stemming
- [ ] Input text lemmatization
- [ ] #88

#### GUI

- [ ] All listed functionalities must have a GUI
