### ISSUE TITLE
Export classified and unclassified data

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Classifier#89]
> [!IMPORTANT]
> The scope of this issue is to cover already anonymized data

AS A Service Manager
I WANT TO export classified data
SO THAT I could use it for whatever reasons applicable

### Acceptance Criteria

- [ ] The scope of data to be exported can limited by using applicable filtering and search the criteria
- [ ] Download selected unclassified (original input) text
- [ ] Download selected classified text

#### Supported file formats

- [ ] Export data as a CSV file
- [ ] Export data as a JSON file
- [ ] Export data as YAML file

#### DSL

- [ ] Use [Data Mapper](https://github.com/buerokratt/DataMapper) for file type and structure conversion

#### GUI

- [ ] #127

##### Filtering

- [ ] By default, filtering options to find relevant text extends to all data columns in use
- [ ] Filtering options actually used in GUI can be defined as a `key-value` pair in a configuration file
