### ISSUE TITLE
Classifier and Jira integration

### ISSUE THREAD

**Issue by vaunapuu** [buerokratt/Classifier#9]
AS A Product Owner
I WANT the Classifier to have integration with Jira Service Desk
SO THAT its input could be used by the Classifier for further processing

### Acceptance Criteria

- [ ] #95
- [ ] #93
- [ ] #133
- [ ] #132

#### _Acceptance Criteria (deprecated)_

- [ ] ~Receive full ticket information in `JSON`~
- [ ] #95
- [ ] #93
- [ ] Pre-process input for further processing by the Classifier
- [ ] Classifier to respond Jira with processed result
- [ ] ~#10~
- [ ] ~#11~
- [ ] ~#12~

### Relevant documentation

- [JIRA Servicedesk API documentation](https://docs.atlassian.com/jira-servicedesk/REST/3.6.2)
