### ISSUE TITLE
Manipulation of datasets used to train data models

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Classifier#90]
AS A Data Scientist
I WANT TO manipulate datasets used to train data models
SO THAT I could improve the precision of trained models

### Acceptance Criteria

- [ ] List all available datasets
- [ ] Define datasets to train a specific model (@vaunapuu please confirm, contradicts with #65)

#### CRUD operations

- [ ] Changes can be made within all fields of an existing dataset
- [ ] Every single dataset can be edited
- [ ] Datasets that are linked with a data model can be disabled if there is no link to #31
- [ ] Datasets that are linked with a data model can't be deleted until the link is destroyed via #31

#### GUI

- [ ] All functionalities can be used via GUI

**Comment by turnerrainer** [comment]
Close as obsolete as it's been covered as part of other similar, already groomed issues within #105
