### ISSUE TITLE
Classifier's data models management

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Classifier#91]
AS A Data Scientist
I WANT TO manage Classifier's data models
SO THAT I could have an overview of existing models, their status, etc. and change their availability in different environments

### Acceptance Criteria

- [ ] Allowed environment labels for data models are defined as configuration settings
> `dev`, `test`, `stage`, `prod`
- [ ] Data models can be labeled within the scope of predefined environment types
- [ ] Same data model can be labeled for more than 1 environment
- [ ] Only one model can be labeled as ready to be used per given environment
- [ ] #130 after their environment-specific labels have been changed

#### GUI

- [ ] #129

#### Scope of environments

- [ ] `dev` for active development purposes, mostly used by developers to test functionality, not the model itself
- [ ] `test` to test trained models
- [ ] `stage` to re-validate trained models that are meant to be used in `stage` without further changes
- [ ] `prod` to use models in live
