### ISSUE TITLE
Model training and storage

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Classifier#92]
AS A Data Scientist
I WANT TO train and store models
SO THAT I could group data models based on their use (e.g. Jira, Outlook, Pinal) and define their maturity level

### Acceptance Criteria

- [ ] List all data models with applicable information regardless of their groups
- [ ] Data model groups are defined as configuration variables and can not be manged via GUI or DSLs on CRUD level
> _Default model groups are `Jira`, `Outlook`, and `Pinal`_
- [ ] Have a separate group for models that haven't been linked to any predefined groups
- [ ] Assign data models to any groups on CRUD level
- [ ] Train new models or new versions of them per data model group
